### ISSUE TITLE
Task: Modify the data structure returned following a scores request to be more easily parsable by python

### ISSUE THREAD

**Issue by Fehings** [Organ-Quality-Assessment/orqa-strapi#15]
### Summary

The current structure returned by the post request takes a bit of fiddling to get into a manageable state in the notebooks. This could be avoided with an easier to parse structure

### What needs to be done?

- [ ] Need to figure out what the ideal structure should actually look like! (FT needs to get on this..)
- [ ] Need to amend the structure with lodash to fit the desired specs 

### Who can help?

FT to think about the structure needed. Then will likely need help from KC or DH to implement pretty please.

### Which user story does this task relate to?

Add here. #

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by KateCourt** [comment]
Create a new endpoint for this specifically for Python access.

**Comment by Fehings** [comment]
So, the new endpoint that Kate made for getting all scored images (that we are currently using) basically fixes this problem and makes it a non-issue! Therefore I am closing this issue as complete.
